menu:
  首页: /
  存档: /archives
  关于: /about
  推荐: /recommend
  My Career: /my-career

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook: junvzhao
google_plus:
twitter: 
github: wahyd4

fancybox: true
google_analytics: UA-5243064-16
rss:

#Google adsense
adsense_enable: true
adsense_id: pub-2599506592075808
